### ISSUE TITLE
Drag and drop is broken

### ISSUE THREAD

**Issue by ilikecola** [leipert/vsb#80]
After clone latest develop branch, the function of subject drag and property drop is broken in dist.
And there is a TypeError, "n is not a function" 

Chrome:
assets-672e1304aa.js:18 TypeError: n is not a function
    at r (http://localhost/scripts/scripts-b7ac52ed6e.js:2:6926)
    at ie (http://localhost/scripts/assets-672e1304aa.js:16:31459)
    at m (http://localhost/scripts/assets-672e1304aa.js:16:25443)
    at s (http://localhost/scripts/assets-672e1304aa.js:16:21552)
    at s (http://localhost/scripts/assets-672e1304aa.js:16:21575)
    at s (http://localhost/scripts/assets-672e1304aa.js:16:21575)
    at m (http://localhost/scripts/assets-672e1304aa.js:16:25392)
    at http://localhost/scripts/assets-672e1304aa.js:16:29203
    at s (http://localhost/scripts/assets-672e1304aa.js:16:21552)
    at http://localhost/scripts/assets-672e1304aa.js:16:20993 <i class="fa fa-fw fa-ellipsis-h hidden-print ng-scope" data-container="body" bs-dropdown="vm.dropdownConfig" bs-model="property"> 

Waiting for your reply! Thank you!

**Comment by Mrpaker** [comment]
Is this problem solved?

**Comment by Mrpaker** [comment]
I fixed it! 
run this:
bower install jquery-ui

**Comment by e-elezi** [comment]
> I fixed it!
> run this:
> bower install jquery-ui

Hey I tried that, but the drag and drop still appears to be broken. Is that the only thing you fixed and also which jquery version did you install?
